-- 코드를 입력하세요
SELECT
    I.ANIMAL_ID, I.NAME
FROM
    ANIMAL_INS AS I
INNER JOIN ANIMAL_OUTS AS O USING (ANIMAL_ID)
ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) DESC
LIMIT 2;

# SELECT
#     I.ANIMAL_ID, I.NAME, DATEDIFF(O.DATETIME,I.DATETIME )
# FROM
#     ANIMAL_INS AS I
# INNER JOIN ANIMAL_OUTS AS O USING (ANIMAL_ID);